### ISSUE TITLE
데이터셋 오류

### ISSUE THREAD

**Issue by issess** [smilegate-ai/korean_unsmile_dataset#1]
760 따로 글 파서 워념 가라 이기야	0	0	0	0	0	0	0	0	0	1	0

해당 항목 clean으로 분류 되어있습니다.

**Comment by smilegate-ai** [comment]
'워념'의 경우, 워마드의 게시판을 지칭하는 표현입니다.
'이기야'의 경우, 어원을 따진다면 특정 인물을 비하하는 발언으로써 시작되었으나, 최근에는 끝말을 표현하는 인터넷의 밈으로 성격이 변하였습니다.
해당 문장의 경우, 본 데이터셋의 태깅 규칙에 따르면 clean이 맞습니다.

1. 특정 집단을 지칭하지 않습니다.
2. 특정 개인을 지칭하지 않습니다.
3. 욕설이나 비하, 혐오성, 불쾌감을 주는 발언이 포함되어있지 않습니다.
